adminapp/urls.py
from django.urls import path

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.index, name='index'), 
    path('users/', adminapp.UserListView.as_view(), name='admin_users'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='admin_users_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='admin_users_update'),
    path('users/remove/<int:pk>/', adminapp.UserDeleteView.as_view(), name='admin_users_remove'),
    path('product_categories/', adminapp.ProductCategoriesListView.as_view(), name='admin_product_categories'),
    path('product_categories/update/<int:pk>/', adminapp.ProductCategoriesUpdateView.as_view(), name='admin_product_categories_update'),
    path('product_categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='admin_product_categories_create'),
    path('product_categories/remove/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='admin_product_categories_remove'),
]

authapp/urls.py
from django.urls import path

from authapp import views as auth_views

app_name = 'authapp'

urlpatterns = [
    path('login/', auth_views.login, name='login'), 
    path('register/', auth_views.register, name='register'),
    path('logout/', auth_views.logout, name='logout'),
    path('profile/', auth_views.profile, name='profile'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import UserRegisterForm, UserProfileForm
from authapp.models import User
from mainapp.models import ProductCategory


class UserAdminRegisterForm(UserRegisterForm):
    avatar = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'


class UserAdminProfileForm(UserProfileForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = False
        self.fields['email'].widget.attrs['readonly'] = False

class UserAdminCreateProductForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Введите название категории'
        self.fields['description'].widget.attrs['placeholder'] = 'Введите описание'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from authapp.models import User
from mainapp.models import ProductCategory
from adminapp.forms import UserAdminRegisterForm, UserAdminProfileForm, UserAdminCreateProductForm

@user_passes_test(lambda u: u.is_superuser)
def index(request):
    return render(request, 'adminapp/index.html')


class UserListView(ListView):
    model = User
    template_name = 'adminapp/admin-users-read.html'
    paginate_by = 3

# @user_passes_test(lambda u: u.is_superuser)
# def admin_users(request):
   
#     context = {
#         'users': User.objects.all(),
#     }
#     return render(request, 'adminapp/admin-users-read.html', context)


class UserCreateView(CreateView):
    model = User
    template_name = 'adminapp/admin-users-create.html'
    success_url = reverse_lazy('admin_staff:admin_users')
    form_class = UserAdminRegisterForm

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserCreateView, self).dispatch(request, *args, **kwargs)

# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_create(request):
   
#     if request.method == 'POST':
#         form = UserAdminRegisterForm(data=request.POST, files=request.FILES)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin_staff:admin_users'))
#         else:
#             print(form.errors)
#     else:
#         form = UserAdminRegisterForm()
#     context = {'form': form}
#     return render(request, 'adminapp/admin-users-create.html', context)


class UserUpdateView(UpdateView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users')
    form_class = UserAdminProfileForm

    def get_context_data(self, **kwargs):  # добавление контекста
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        context.update({'title': 'Geekshop - редактирование пользователя'})
        return context

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(UserUpdateView, self).dispatch(request, *args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_update(request, user_id):
#     user = User.objects.get(id=user_id)
#     if request.method == 'POST':
#         form = UserAdminProfileForm(data=request.POST, files=request.FILES, instance=user)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin_staff:admin_users'))
#     else:
#         form = UserAdminProfileForm(instance=user)

#     context = {'form': form, 'user': user}
#     return render(request, 'adminapp/admin-users-update-delete.html', context)


class UserDeleteView(DeleteView):
    model = User
    template_name = 'adminapp/admin-users-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_users')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

# @user_passes_test(lambda u: u.is_superuser)
# def admin_users_remove(request, user_id):
#     user = User.objects.get(id=user_id)
#     # user.delete()
#     user.is_active = False
#     user.save()
#     return HttpResponseRedirect(reverse('admin_staff:admin_users'))


class ProductCategoriesListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/admin-product_categories-read.html'
    paginate_by = 2

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductCategoriesListView, self).dispatch(request, *args, **kwargs)

# @user_passes_test(lambda u: u.is_superuser)
# def admin_product_categories(request):
#     context = {
#         'product_categories': ProductCategory.objects.all(),
#     }

#     return render(request, 'adminapp/admin-product_categories-read.html', context)

class ProductCategoriesUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/admin-product_categories-update-delete.html'
    success_url = reverse_lazy('admin_staff:admin_product_categories')
    form_class = UserAdminCreateProductForm

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductCategoriesUpdateView, self).dispatch(request, *args, **kwargs)

# @user_passes_test(lambda u: u.is_superuser)
# def admin_product_categories_update(request, product_category_id):
#     category = ProductCategory.objects.get(id=product_category_id)
#     if request.method == 'POST':
#         form = UserAdminCreateProductForm(data=request.POST, instance=category)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin_staff:admin_product_categories'))
#     else:
#         form = UserAdminCreateProductForm(instance=category)

#     context = {'form': form, 'product_category': category}
#     return render(request, 'adminapp/admin-product_categories-update-delete.html', context)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/admin-product_categories-create.html'
    success_url = reverse_lazy('admin_staff:admin_product_categories')
    form_class = UserAdminCreateProductForm

    @method_decorator(user_passes_test(lambda user: user.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super(ProductCategoryCreateView, self).dispatch(request, *args, **kwargs)

# @user_passes_test(lambda u: u.is_superuser)
# def admin_product_categories_create(request):
#     if request.method == 'POST':
#         form = UserAdminCreateProductForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('admin_staff:admin_product_categories'))
#         else:
#             print(form.errors)
#     else:
#         form = UserAdminCreateProductForm()

#     context = {'form': form}
#     return render(request, 'adminapp/admin-product_categories-create.html', context)

class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    success_url = reverse_lazy('admin_staff:admin_product_categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

# @user_passes_test(lambda u: u.is_superuser)
# def admin_product_categories_remove(request, product_category_id):
#     category = ProductCategory.objects.get(id=product_category_id)
#     category.delete()
#     return HttpResponseRedirect(reverse('admin_staff:admin_product_categories'))

adminapp/templates/adminapp/admin-product_categories-create.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Создание категории</h1>
    <form action="{% url 'admin_staff:admin_product_categories_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Название</label>
                    {{ form.name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Описание</label>
                    {{ form.description }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
{% endblock %}

adminapp/templates/adminapp/admin-product_categories-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
<h1 class="mt-4">Категории товаров</h1>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Категории
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Название категории</th>
                    <th>Описание</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>Название категории</th>
                    <th>Описание</th>
                </tr>
                </tfoot>
                <tbody>
                {% for product_category in object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'admin_staff:admin_product_categories_update' product_category.id %}" style="color: dodgerblue">
                                {{ product_category.name }}
                            </a>
                        </td>
                        <td>{{ product_category.description }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% if is_paginated %}
    <ul class="pagination">
        <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %} ">
            <a class="page-link"
               href="
                    {% if not page_obj.has_previous %}
                    #
                    {% else %}
                    {% url 'admin_staff:admin_product_categories' %}?page={{ page_obj.previous_page_number }}
                    {% endif %}">
                Предыдущая
            </a>
        </li>
        {% for page in page_obj.paginator.page_range %}
            <li class="page-item">
                <a class="page-link"
                   href="{% url 'admin_staff:admin_product_categories' %}?page={{ page }}">{{ page }}
                </a>
            </li>
        {% endfor %}
        <li class="page-item {% if not page_obj.has_next %} disabled {% endif %} ">
            <a class="page-link"
               href="
                    {% if not page_obj.has_next %}
                    #
                    {% else %}
                    {% url 'admin_staff:admin_product_categories' %}?page={{ page_obj.next_page_number }} {% endif %}">
                Следующая
            </a>
        </li>
    </ul>
    {% endif %}

    <div class="card-footer">
        <button class="btn btn-success">
            <a href="{% url 'admin_staff:admin_product_categories_create' %}" style="color: white;">
                Создать категорию
            </a>
        </button>
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/admin-product_categories-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Редактирование категорий</h1>
    <div class="card-body">
        <form action="{% url 'admin_staff:admin_product_categories_update' productcategory.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                        {{ form.name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                        {{ form.description }}
                    </div>
                </div>
            </div>            
           
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <form action="{% url 'admin_staff:admin_product_categories_remove' productcategory.id %}">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/admin-users-create.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Создание пользователя</h1>
    <form action="{% url 'admin_staff:admin_users_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                    {{ form.last_name }}
                </div>
            </div>
        </div>
        <div class="form-row mb-2">
            <div class="col-lg-12">
                <div class="custom-file">
                    {{ form.avatar }}
                    <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите изображение</label>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                {{ form.username }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                    почты</label>
                {{ form.email }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                {{ form.password1 }}
            </div>
            <div class="col-lg-6">
                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Повторите пароль</label>
                {{ form.password2 }}
            </div>
        </div>
        <div class="form-row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <input class="btn btn-info btn-block" type="submit" value="Сохранить">
            </div>
        </div>
    </form>
{% endblock %}

adminapp/templates/adminapp/admin-users-read.html
{% extends 'adminapp/base.html' %}

{% block content %}
<h1 class="mt-4">Пользователи</h1>
<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table mr-1"></i>
        Пользователи
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>Имя пользователя</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Адрес эл. почты</th>
                    <th>Персонал сайта</th>
                    <th>Активный</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>Имя пользователя</th>
                    <th>Имя</th>
                    <th>Фамилия</th>
                    <th>Адрес эл. почты</th>
                    <th>Персонал сайта</th>
                    <th>Активный</th>
                </tr>
                </tfoot>
                <tbody>
                {% for user in object_list %}
                    <tr>
                        <td>
                            <a href="{% url 'admin_staff:admin_users_update' user.id %}" style="color: dodgerblue">
                                {{ user.username }}
                            </a>
                        </td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.email }}</td>
                        <td class="text-center">
                            {% if user.is_staff %}
                                <i class="fas fa-check-circle"></i>
                            {% else %}
                                <i class="fas fa-times-circle"></i>
                            {% endif %}
                        </td>
                        <td class="text-center">
                            {% if user.is_active %}
                                <i class="fas fa-check-circle"></i>
                            {% else %}
                                <i class="fas fa-times-circle"></i>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer">
        <button class="btn btn-success">
            <a href="{% url 'admin_staff:admin_users_create' %}" style="color: white;">
                Создать пользователя
            </a>
        </button>
        {% if is_paginated %}
                <ul class="pagination">
                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %} ">
                        <a class="page-link"
                           href="
                            {% if not page_obj.has_previous %}
                             #
                            {% else %}
                            {% url 'admin_staff:admin_users' %}?page={{ page_obj.previous_page_number }}
                            {% endif %}">
                            Предыдущая
                        </a>
                    </li>
                    {% for page in page_obj.paginator.page_range %}
                        <li class="page-item">
                            <a class="page-link"
                               href="{% url 'admin_staff:admin_users' %}?page={{ page }}">{{ page }}
                            </a>
                        </li>
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %} ">
                        <a class="page-link"
                           href="
                            {% if not page_obj.has_next %}
                            #
                            {% else %}
                            {% url 'admin_staff:admin_users' %}?page={{ page_obj.next_page_number }} {% endif %}">
                            Следующая
                        </a>
                    </li>
                </ul>
            {% endif %}
    </div>
</div>
{% endblock %}

adminapp/templates/adminapp/admin-users-update-delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
    <div class="card-body">
        <form action="{% url 'admin_staff:admin_users_update' user.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="col-lg-12">
                    <div class="custom-file">
                        {{ form.avatar }}
                        <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">Выберите
                            изображение</label>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                    {{ form.username }}
                </div>
                <div class="col-lg-6">
                    <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                        почты</label>
                    {{ form.email }}
                </div>
            </div>
            <div class="form-row">
                <div class="col-lg-12" style="margin-top: 33px;">
                    <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                </div>
            </div>
        </form>
        <div class="row">
            <div class="col-lg-12" style="margin-top: 33px;">
                <form action="{% url 'admin_staff:admin_users_remove' user.id %}">
                    <input class="btn btn-danger btn-block" type="submit" value="Удалить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

adminapp/templates/adminapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Admin</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
    {#    <script src="../../../../../Desktop/startbootstrap-sb-admin-gh-pages/dist/js/scripts.js"></script>#}
    {#    <script src="../../../../../Desktop/startbootstrap-sb-admin-gh-pages/dist/assets/demo/datatables-demo.js"></script>#}
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'main' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="{% url 'main' %}"><i
            class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'auth:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admin_staff:admin_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admin_staff:admin_product_categories' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Категории
                    </a>
                    <a class="nav-link" href="#">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </main>
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop 2020</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>

adminapp/templates/adminapp/index.html
{% extends 'adminapp/base.html' %}

{% block content %}
    <h1 class="mt-4">Административная панель</h1>
{% endblock %}